# Generated by Django 4.1.6 on 2024-03-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category_tree",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.category",
            ),
            preserve_default=False,
        ),
    ]
