# Generated by Django 4.1.6 on 2024-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_remove_item_category_tree_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
